package app.minimercado.domain;

public enum CategoriaProduto {
SALGADOS, DOCES, BEBIDAS_GELADAS, BEBIDAS_QUENTES, AVE_MARIA, SEGUEME;
//    BEBIDAS,LANCHES,DOCES,SEGUEME,AVE_MARIA,PAGAMENTO, COMBOS
}
